
package vendingmachine;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author jasperadrada
 */
public class AskProduct extends javax.swing.JFrame {

    private String userInput;
    private String newStock;
    public static int chosenItem;
    RegularVendingMachine RVM = new RegularVendingMachine();
 
    
    public AskProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        itemCal1 = new javax.swing.JLabel();
        itemPrice1 = new javax.swing.JLabel();
        itemStock1 = new javax.swing.JLabel();
        itemPrice2 = new javax.swing.JLabel();
        itemStock2 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        itemCal2 = new javax.swing.JLabel();
        itemCal3 = new javax.swing.JLabel();
        itemPrice3 = new javax.swing.JLabel();
        itemStock3 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();
        itemCal4 = new javax.swing.JLabel();
        itemPrice4 = new javax.swing.JLabel();
        itemStock4 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        itemStock5 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        itemCal5 = new javax.swing.JLabel();
        itemPrice5 = new javax.swing.JLabel();
        itemStock6 = new javax.swing.JLabel();
        item6 = new javax.swing.JLabel();
        itemCal6 = new javax.swing.JLabel();
        itemPrice6 = new javax.swing.JLabel();
        itemStock7 = new javax.swing.JLabel();
        item7 = new javax.swing.JLabel();
        itemCal7 = new javax.swing.JLabel();
        itemPrice7 = new javax.swing.JLabel();
        itemStock8 = new javax.swing.JLabel();
        item8 = new javax.swing.JLabel();
        itemCal8 = new javax.swing.JLabel();
        itemPrice8 = new javax.swing.JLabel();
        itemCal9 = new javax.swing.JLabel();
        itemPrice9 = new javax.swing.JLabel();
        itemStock9 = new javax.swing.JLabel();
        item9 = new javax.swing.JLabel();
        itemCal10 = new javax.swing.JLabel();
        itemPrice10 = new javax.swing.JLabel();
        itemStock10 = new javax.swing.JLabel();
        item10 = new javax.swing.JLabel();
        itemCal11 = new javax.swing.JLabel();
        itemPrice11 = new javax.swing.JLabel();
        itemStock11 = new javax.swing.JLabel();
        item11 = new javax.swing.JLabel();
        itemCal12 = new javax.swing.JLabel();
        itemPrice12 = new javax.swing.JLabel();
        itemStock12 = new javax.swing.JLabel();
        item12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        itemSelection = new javax.swing.JTextField();
        CTP = new javax.swing.JButton();
        newStockk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel1.setText("WELCOME TO SILOGAN");

        item1.setText("BROWN RICE");

        itemCal1.setText("CALORIES: 216");

        itemPrice1.setText("PRICE: 30");

        itemStock1.setText("QUANTITY: 15");

        itemPrice2.setText("PRICE: 15");

        itemStock2.setText("QUANTITY: 15");

        item2.setText("WHITE RICE");

        itemCal2.setText("CALORIES: 206");

        itemCal3.setText("CALORIES: 169");

        itemPrice3.setText("PRICE: 20");

        itemStock3.setText("QUANTITY: 15");

        item3.setText("JAVA RICE");

        itemCal4.setText("CALORIES: 33");

        itemPrice4.setText("PRICE: 30");

        itemStock4.setText("QUANTITY: 15");

        item4.setText("BACON BITS");

        itemStock5.setText("QUANTITY: 15");

        item5.setText("ROASTED MSUHROOMS");

        itemCal5.setText("CALORIES: 20");

        itemPrice5.setText("PRICE: 15");

        itemStock6.setText("QUANTITY: 15");

        item6.setText("EDAMAME");

        itemCal6.setText("CALORIES: 12");

        itemPrice6.setText("PRICE: 15");

        itemStock7.setText("QUANTITY: 15");

        item7.setText("GRILLED CHICKEN");

        itemCal7.setText("CALORIES: 147");

        itemPrice7.setText("PRICE: 45");

        itemStock8.setText("QUANTITY: 15");

        item8.setText("GROUND BEEF");

        itemCal8.setText("CALORIES: 100");

        itemPrice8.setText("PRICE: 55");

        itemCal9.setText("CALORIES: 197");

        itemPrice9.setText("PRICE: 65");

        itemStock9.setText("QUANTITY: 15");

        item9.setText("MEATBALLS");

        itemCal10.setText("CALORIES: 178");

        itemPrice10.setText("PRICE: 30");

        itemStock10.setText("QUANTITY: 15");

        item10.setText("SALMON");

        itemCal11.setText("CALORIES: 16");

        itemPrice11.setText("PRICE: 30");

        itemStock11.setText("QUANTITY: 15");

        item11.setText("TERIYAKI SAUCE");

        itemCal12.setText("CALORIES: 110");

        itemPrice12.setText("PRICE: 30");

        itemStock12.setText("QUANTITY: 15");

        item12.setText("CHEESE SAUCE");

        jLabel2.setText("ITEM 1");

        jLabel3.setText("ITEM 2");

        jLabel4.setText("ITEM 3");

        jLabel5.setText("ITEM 5");

        jLabel6.setText("ITEM 4");

        jLabel7.setText("ITEM 6");

        jLabel8.setText("ITEM 7");

        jLabel9.setText("ITEM 8");

        jLabel10.setText("ITEM 9");

        jLabel11.setText("ITEM 11");

        jLabel12.setText("ITEM 10");

        jLabel13.setText("ITEM 12");

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        itemSelection.setText("CHOOSE AN ITEM:  (PRESS ENTER BEFORE HITTING CONTINUE TO PAYMENT)");
        itemSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSelectionActionPerformed(evt);
            }
        });

        CTP.setText("CONTINUE ");
        CTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTPActionPerformed(evt);
            }
        });

        newStockk.setText("ENTER THE AMOUNT OF NEW STOCK:  (PRESS ENTER BEFORE HITTING CONTINUE TO PAYMENT)");
        newStockk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStockkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newStockk, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(itemSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(item7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemCal7)
                                            .addGap(77, 77, 77)
                                            .addComponent(itemPrice7)
                                            .addGap(58, 58, 58)
                                            .addComponent(itemStock7))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(item8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemCal8)
                                            .addGap(77, 77, 77)
                                            .addComponent(itemPrice8)
                                            .addGap(58, 58, 58)
                                            .addComponent(itemStock8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(item9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemCal9)
                                            .addGap(77, 77, 77)
                                            .addComponent(itemPrice9)
                                            .addGap(58, 58, 58)
                                            .addComponent(itemStock9))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(item10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemCal10)
                                            .addGap(77, 77, 77)
                                            .addComponent(itemPrice10)
                                            .addGap(58, 58, 58)
                                            .addComponent(itemStock10))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(item11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemCal11)
                                            .addGap(77, 77, 77)
                                            .addComponent(itemPrice11)
                                            .addGap(58, 58, 58)
                                            .addComponent(itemStock11))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(item1)
                                                .addComponent(item2)
                                                .addComponent(item3)
                                                .addComponent(item4)
                                                .addComponent(item5)
                                                .addComponent(item6))
                                            .addGap(81, 81, 81)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(itemCal1)
                                                        .addComponent(itemCal2)
                                                        .addComponent(itemCal3)
                                                        .addComponent(itemCal4)
                                                        .addComponent(itemCal5))
                                                    .addGap(77, 77, 77)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(itemPrice1)
                                                        .addComponent(itemPrice2)
                                                        .addComponent(itemPrice3)
                                                        .addComponent(itemPrice4)
                                                        .addComponent(itemPrice5)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(itemCal6)
                                                    .addGap(77, 77, 77)
                                                    .addComponent(itemPrice6)))
                                            .addGap(58, 58, 58)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(itemStock6)
                                                .addComponent(itemStock5)
                                                .addComponent(itemStock4)
                                                .addComponent(itemStock3)
                                                .addComponent(itemStock2)
                                                .addComponent(itemStock1)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(item12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(itemCal12)
                                            .addGap(77, 77, 77)
                                            .addComponent(itemPrice12)
                                            .addGap(58, 58, 58)
                                            .addComponent(itemStock12))))
                                .addComponent(CTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item1)
                            .addComponent(itemCal1)
                            .addComponent(itemStock1)
                            .addComponent(itemPrice1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item2)
                            .addComponent(itemCal2)
                            .addComponent(itemPrice2)
                            .addComponent(itemStock2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item3)
                            .addComponent(itemCal3)
                            .addComponent(itemPrice3)
                            .addComponent(itemStock3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item4)
                            .addComponent(itemCal4)
                            .addComponent(itemPrice4)
                            .addComponent(itemStock4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item5)
                            .addComponent(itemCal5)
                            .addComponent(itemPrice5)
                            .addComponent(itemStock5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item6)
                            .addComponent(itemCal6)
                            .addComponent(itemPrice6)
                            .addComponent(itemStock6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item7)
                            .addComponent(itemCal7)
                            .addComponent(itemPrice7)
                            .addComponent(itemStock7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item8)
                            .addComponent(itemCal8)
                            .addComponent(itemPrice8)
                            .addComponent(itemStock8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item9)
                            .addComponent(itemCal9)
                            .addComponent(itemPrice9)
                            .addComponent(itemStock9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item10)
                            .addComponent(itemCal10)
                            .addComponent(itemPrice10)
                            .addComponent(itemStock10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item11)
                            .addComponent(itemCal11)
                            .addComponent(itemPrice11)
                            .addComponent(itemStock11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item12)
                            .addComponent(itemCal12)
                            .addComponent(itemPrice12)
                            .addComponent(itemStock12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(itemSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(newStockk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CTP)
                .addGap(12, 12, 12)
                .addComponent(back)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MaintenanceGui back = new MaintenanceGui();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void itemSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSelectionActionPerformed
        // TODO add your handling code here:
        // get the user input from the text field  
        String choice = itemSelection.getText().strip();
        this.userInput = choice;
        
    }//GEN-LAST:event_itemSelectionActionPerformed

    private void CTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTPActionPerformed
        
        RegularVendingMachine RVM = new RegularVendingMachine();
        Maintenance main = new Maintenance();
        int choice;
        int stock;
        if (userInput == null && newStock == null) {
            JOptionPane.showMessageDialog(null, """
                                                Make sure to fill out the text field with a valid input
                                                Don't forget to press enter at the Text Field before continuing to payment                               
                                                """);
        }
        
        else if (userInput != null && newStock != null) {
            choice = Integer.parseInt(userInput);
            
            if (choice < 1 && choice > 12) {
                JOptionPane.showMessageDialog(null, "Please enter a valid input (1 - 12)");
            }
            
            else {
                this.chosenItem = choice;
                RVM.selectedProduct = chosenItem;
                int pharsa = Integer.parseInt(newStock);
                main.restockOneProduct(choice, pharsa);
                        
                
                
                PaymentGUI go = new PaymentGUI();
                go.setVisible(true);
          
                this.dispose();
                
            }
        }
        
          
            
    }//GEN-LAST:event_CTPActionPerformed

    private void newStockkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStockkActionPerformed
        // TODO add your handling code here:String choice = itemSelection.getText().strip();
        String choice = newStockk.getText().strip();
        this.newStock = choice;
    }//GEN-LAST:event_newStockkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AskProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CTP;
    private javax.swing.JButton back;
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item10;
    private javax.swing.JLabel item11;
    private javax.swing.JLabel item12;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel item4;
    private javax.swing.JLabel item5;
    private javax.swing.JLabel item6;
    private javax.swing.JLabel item7;
    private javax.swing.JLabel item8;
    private javax.swing.JLabel item9;
    private javax.swing.JLabel itemCal1;
    private javax.swing.JLabel itemCal10;
    private javax.swing.JLabel itemCal11;
    private javax.swing.JLabel itemCal12;
    private javax.swing.JLabel itemCal2;
    private javax.swing.JLabel itemCal3;
    private javax.swing.JLabel itemCal4;
    private javax.swing.JLabel itemCal5;
    private javax.swing.JLabel itemCal6;
    private javax.swing.JLabel itemCal7;
    private javax.swing.JLabel itemCal8;
    private javax.swing.JLabel itemCal9;
    private javax.swing.JLabel itemPrice1;
    private javax.swing.JLabel itemPrice10;
    private javax.swing.JLabel itemPrice11;
    private javax.swing.JLabel itemPrice12;
    private javax.swing.JLabel itemPrice2;
    private javax.swing.JLabel itemPrice3;
    private javax.swing.JLabel itemPrice4;
    private javax.swing.JLabel itemPrice5;
    private javax.swing.JLabel itemPrice6;
    private javax.swing.JLabel itemPrice7;
    private javax.swing.JLabel itemPrice8;
    private javax.swing.JLabel itemPrice9;
    public static javax.swing.JTextField itemSelection;
    public static javax.swing.JLabel itemStock1;
    public static javax.swing.JLabel itemStock10;
    public static javax.swing.JLabel itemStock11;
    public static javax.swing.JLabel itemStock12;
    public static javax.swing.JLabel itemStock2;
    public static javax.swing.JLabel itemStock3;
    public static javax.swing.JLabel itemStock4;
    public static javax.swing.JLabel itemStock5;
    public static javax.swing.JLabel itemStock6;
    public static javax.swing.JLabel itemStock7;
    public static javax.swing.JLabel itemStock8;
    public static javax.swing.JLabel itemStock9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField newStockk;
    // End of variables declaration//GEN-END:variables
}
