/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachine;

/**
 *
 * @author jasperadrada
 */
public class CustomerSVGUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerGUI
     */
    public CustomerSVGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        item1 = new javax.swing.JLabel();
        itemCal1 = new javax.swing.JLabel();
        itemPrice1 = new javax.swing.JLabel();
        itemStock1 = new javax.swing.JLabel();
        itemPrice2 = new javax.swing.JLabel();
        itemStock2 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        item2 = new javax.swing.JLabel();
        itemCal2 = new javax.swing.JLabel();
        itemCal3 = new javax.swing.JLabel();
        itemPrice3 = new javax.swing.JLabel();
        itemStock3 = new javax.swing.JLabel();
        B3 = new javax.swing.JButton();
        item3 = new javax.swing.JLabel();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        itemCal4 = new javax.swing.JLabel();
        itemPrice4 = new javax.swing.JLabel();
        itemStock4 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        itemStock5 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        itemCal5 = new javax.swing.JLabel();
        itemPrice5 = new javax.swing.JLabel();
        itemStock6 = new javax.swing.JLabel();
        item6 = new javax.swing.JLabel();
        itemCal6 = new javax.swing.JLabel();
        itemPrice6 = new javax.swing.JLabel();
        itemStock7 = new javax.swing.JLabel();
        item7 = new javax.swing.JLabel();
        itemCal7 = new javax.swing.JLabel();
        itemPrice7 = new javax.swing.JLabel();
        itemStock8 = new javax.swing.JLabel();
        item8 = new javax.swing.JLabel();
        itemCal8 = new javax.swing.JLabel();
        itemPrice8 = new javax.swing.JLabel();
        itemCal9 = new javax.swing.JLabel();
        itemPrice9 = new javax.swing.JLabel();
        itemStock9 = new javax.swing.JLabel();
        item9 = new javax.swing.JLabel();
        itemCal10 = new javax.swing.JLabel();
        itemPrice10 = new javax.swing.JLabel();
        itemStock10 = new javax.swing.JLabel();
        item10 = new javax.swing.JLabel();
        itemCal11 = new javax.swing.JLabel();
        itemPrice11 = new javax.swing.JLabel();
        itemStock11 = new javax.swing.JLabel();
        item11 = new javax.swing.JLabel();
        itemCal12 = new javax.swing.JLabel();
        itemPrice12 = new javax.swing.JLabel();
        itemStock12 = new javax.swing.JLabel();
        item12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SVADD = new javax.swing.JButton();
        CONTINUE = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel1.setText("WELCOME TO SILOGAN");

        B1.setText("1");
        B1.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        item1.setText("BROWN RICE");

        itemCal1.setText("CALORIES: 216");

        itemPrice1.setText("PRICE: 30");

        itemStock1.setText("QUANTITY: 15");

        itemPrice2.setText("PRICE: 30");

        itemStock2.setText("QUANTITY: 15");

        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        item2.setText("WHITE RICE");

        itemCal2.setText("CALORIES: 216");

        itemCal3.setText("CALORIES: 216");

        itemPrice3.setText("PRICE: 30");

        itemStock3.setText("QUANTITY: 15");

        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        item3.setText("JAVA RICE");

        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setText("5");
        B5.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setText("7");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setText("6");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setText("9");
        B9.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B10.setText("11");
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });

        B11.setText("10");
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B12.setText("12");
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });

        itemCal4.setText("CALORIES: 216");

        itemPrice4.setText("PRICE: 30");

        itemStock4.setText("QUANTITY: 15");

        item4.setText("BACON BITS");

        itemStock5.setText("QUANTITY: 15");

        item5.setText("ROASTED MSUHROOMS");

        itemCal5.setText("CALORIES: 216");

        itemPrice5.setText("PRICE: 30");

        itemStock6.setText("QUANTITY: 15");

        item6.setText("EDAMAME");

        itemCal6.setText("CALORIES: 216");

        itemPrice6.setText("PRICE: 30");

        itemStock7.setText("QUANTITY: 15");

        item7.setText("GRILLED CHICKEN");

        itemCal7.setText("CALORIES: 216");

        itemPrice7.setText("PRICE: 30");

        itemStock8.setText("QUANTITY: 15");

        item8.setText("GROUND BEEF");

        itemCal8.setText("CALORIES: 216");

        itemPrice8.setText("PRICE: 30");

        itemCal9.setText("CALORIES: 216");

        itemPrice9.setText("PRICE: 30");

        itemStock9.setText("QUANTITY: 15");

        item9.setText("MEATBALLS");

        itemCal10.setText("CALORIES: 216");

        itemPrice10.setText("PRICE: 30");

        itemStock10.setText("QUANTITY: 15");

        item10.setText("SALMON");

        itemCal11.setText("CALORIES: 216");

        itemPrice11.setText("PRICE: 30");

        itemStock11.setText("QUANTITY: 15");

        item11.setText("TERIYAKI SAUCE");

        itemCal12.setText("CALORIES: 216");

        itemPrice12.setText("PRICE: 30");

        itemStock12.setText("QUANTITY: 15");

        item12.setText("CHEESE SAUCE");

        jLabel2.setText("ITEM 1");

        jLabel3.setText("ITEM 2");

        jLabel4.setText("ITEM 3");

        jLabel5.setText("ITEM 5");

        jLabel6.setText("ITEM 4");

        jLabel7.setText("ITEM 6");

        jLabel8.setText("ITEM 7");

        jLabel9.setText("ITEM 8");

        jLabel10.setText("ITEM 9");

        jLabel11.setText("ITEM 11");

        jLabel12.setText("ITEM 10");

        jLabel13.setText("ITEM 12");

        SVADD.setText("ADD ANOTHER ITEM");

        CONTINUE.setText("CONTINUE");

        jButton3.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(item7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemCal7)
                                .addGap(77, 77, 77)
                                .addComponent(itemPrice7)
                                .addGap(58, 58, 58)
                                .addComponent(itemStock7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(item8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemCal8)
                                .addGap(77, 77, 77)
                                .addComponent(itemPrice8)
                                .addGap(58, 58, 58)
                                .addComponent(itemStock8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(item9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemCal9)
                                .addGap(77, 77, 77)
                                .addComponent(itemPrice9)
                                .addGap(58, 58, 58)
                                .addComponent(itemStock9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemCal10)
                                .addGap(77, 77, 77)
                                .addComponent(itemPrice10)
                                .addGap(58, 58, 58)
                                .addComponent(itemStock10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemCal11)
                                .addGap(77, 77, 77)
                                .addComponent(itemPrice11)
                                .addGap(58, 58, 58)
                                .addComponent(itemStock11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(item1)
                                    .addComponent(item2)
                                    .addComponent(item3)
                                    .addComponent(item4)
                                    .addComponent(item5)
                                    .addComponent(item6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(itemCal6)
                                                .addGap(77, 77, 77)
                                                .addComponent(itemPrice6)
                                                .addGap(58, 58, 58)
                                                .addComponent(itemStock6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(itemCal1)
                                                    .addComponent(itemCal2)
                                                    .addComponent(itemCal3)
                                                    .addComponent(itemCal4)
                                                    .addComponent(itemCal5))
                                                .addGap(77, 77, 77)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(itemPrice1)
                                                    .addComponent(itemPrice2)
                                                    .addComponent(itemPrice3)
                                                    .addComponent(itemPrice4)
                                                    .addComponent(itemPrice5))
                                                .addGap(58, 58, 58)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(itemStock5)
                                                    .addComponent(itemStock4)
                                                    .addComponent(itemStock3)
                                                    .addComponent(itemStock2)
                                                    .addComponent(itemStock1)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemCal12)
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(itemPrice12)
                                        .addGap(58, 58, 58)
                                        .addComponent(itemStock12))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CONTINUE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SVADD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item1)
                            .addComponent(itemCal1)
                            .addComponent(itemStock1)
                            .addComponent(itemPrice1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item2)
                            .addComponent(itemCal2)
                            .addComponent(itemPrice2)
                            .addComponent(itemStock2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item3)
                            .addComponent(itemCal3)
                            .addComponent(itemPrice3)
                            .addComponent(itemStock3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item4)
                            .addComponent(itemCal4)
                            .addComponent(itemPrice4)
                            .addComponent(itemStock4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item5)
                            .addComponent(itemCal5)
                            .addComponent(itemPrice5)
                            .addComponent(itemStock5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item6)
                            .addComponent(itemCal6)
                            .addComponent(itemPrice6)
                            .addComponent(itemStock6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item7)
                            .addComponent(itemCal7)
                            .addComponent(itemPrice7)
                            .addComponent(itemStock7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item8)
                            .addComponent(itemCal8)
                            .addComponent(itemPrice8)
                            .addComponent(itemStock8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item9)
                            .addComponent(itemCal9)
                            .addComponent(itemPrice9)
                            .addComponent(itemStock9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item10)
                            .addComponent(itemCal10)
                            .addComponent(itemPrice10)
                            .addComponent(itemStock10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item11)
                            .addComponent(itemCal11)
                            .addComponent(itemPrice11)
                            .addComponent(itemStock11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item12)
                            .addComponent(itemCal12)
                            .addComponent(itemPrice12)
                            .addComponent(itemStock12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B1)
                        .addGap(18, 18, 18)
                        .addComponent(B5)
                        .addGap(18, 18, 18)
                        .addComponent(B9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B2)
                        .addGap(18, 18, 18)
                        .addComponent(B7)
                        .addGap(18, 18, 18)
                        .addComponent(B11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B3)
                        .addGap(18, 18, 18)
                        .addComponent(B6)
                        .addGap(18, 18, 18)
                        .addComponent(B10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B4)
                            .addComponent(SVADD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B8)
                            .addComponent(CONTINUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(B12)))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B10ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSVGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton CONTINUE;
    private javax.swing.JButton SVADD;
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item10;
    private javax.swing.JLabel item11;
    private javax.swing.JLabel item12;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel item4;
    private javax.swing.JLabel item5;
    private javax.swing.JLabel item6;
    private javax.swing.JLabel item7;
    private javax.swing.JLabel item8;
    private javax.swing.JLabel item9;
    private javax.swing.JLabel itemCal1;
    private javax.swing.JLabel itemCal10;
    private javax.swing.JLabel itemCal11;
    private javax.swing.JLabel itemCal12;
    private javax.swing.JLabel itemCal2;
    private javax.swing.JLabel itemCal3;
    private javax.swing.JLabel itemCal4;
    private javax.swing.JLabel itemCal5;
    private javax.swing.JLabel itemCal6;
    private javax.swing.JLabel itemCal7;
    private javax.swing.JLabel itemCal8;
    private javax.swing.JLabel itemCal9;
    private javax.swing.JLabel itemPrice1;
    private javax.swing.JLabel itemPrice10;
    private javax.swing.JLabel itemPrice11;
    private javax.swing.JLabel itemPrice12;
    private javax.swing.JLabel itemPrice2;
    private javax.swing.JLabel itemPrice3;
    private javax.swing.JLabel itemPrice4;
    private javax.swing.JLabel itemPrice5;
    private javax.swing.JLabel itemPrice6;
    private javax.swing.JLabel itemPrice7;
    private javax.swing.JLabel itemPrice8;
    private javax.swing.JLabel itemPrice9;
    private javax.swing.JLabel itemStock1;
    private javax.swing.JLabel itemStock10;
    private javax.swing.JLabel itemStock11;
    private javax.swing.JLabel itemStock12;
    private javax.swing.JLabel itemStock2;
    private javax.swing.JLabel itemStock3;
    private javax.swing.JLabel itemStock4;
    private javax.swing.JLabel itemStock5;
    private javax.swing.JLabel itemStock6;
    private javax.swing.JLabel itemStock7;
    private javax.swing.JLabel itemStock8;
    private javax.swing.JLabel itemStock9;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
