package vendingmachine;

import javax.swing.JOptionPane;

/**
 *
 * @author jasperadrada
 */
public class PaymentGUI extends javax.swing.JFrame {

    /**
     * Creates new form PaymentGUI
     */
    public PaymentGUI() {
        initComponents();
    }

    RegularVendingMachine RVM = new RegularVendingMachine();
    CustomerRVGUI CST = new CustomerRVGUI();
    PaymentBundle change;
    String payment1;
    String payment5;
    String payment10;
    String payment20;
    String payment50;
    String payment100;
    String payment200;
    String payment500;
    String payment1000;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        peso1 = new javax.swing.JTextField();
        peso5 = new javax.swing.JTextField();
        peso10 = new javax.swing.JTextField();
        peso20 = new javax.swing.JTextField();
        peso50 = new javax.swing.JTextField();
        peso100 = new javax.swing.JTextField();
        peso200 = new javax.swing.JTextField();
        peso500 = new javax.swing.JTextField();
        peso1000 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FinTrans = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("5");

        jLabel2.setText("1  ");

        jLabel3.setText("10");

        jLabel4.setText("20");

        jLabel5.setText("50");

        jLabel6.setText("200");

        jLabel7.setText("100");

        jLabel8.setText("500");

        jLabel9.setText("1000");

        peso1.setText("Enter Amount");
        peso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso1ActionPerformed(evt);
            }
        });

        peso5.setText("Enter Amount");
        peso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso5ActionPerformed(evt);
            }
        });

        peso10.setText("Enter Amount");
        peso10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso10ActionPerformed(evt);
            }
        });

        peso20.setText("Enter Amount");
        peso20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso20ActionPerformed(evt);
            }
        });

        peso50.setText("Enter Amount");
        peso50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso50ActionPerformed(evt);
            }
        });

        peso100.setText("Enter Amount");
        peso100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso100ActionPerformed(evt);
            }
        });

        peso200.setText("Enter Amount");
        peso200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso200ActionPerformed(evt);
            }
        });

        peso500.setText("Enter Amount");
        peso500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso500ActionPerformed(evt);
            }
        });

        peso1000.setText("Enter Amount");
        peso1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso1000ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("ENTER THE AMOUNT OF PAYMENT ");

        FinTrans.setText("FINISH TRANSACTION");
        FinTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinTransActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(FinTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(peso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(peso10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(peso20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(peso50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(peso100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(peso200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(peso500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(peso1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(FinTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peso10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso10ActionPerformed
        // TODO add your handling code here:
        this.payment10 = peso10.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso10ActionPerformed

    private void peso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso1ActionPerformed
        // TODO add your handling code here:
        this.payment1 = peso1.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso1ActionPerformed

    private void peso20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso20ActionPerformed
        // TODO add your handling code here:
        this.payment20 = peso20.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso20ActionPerformed

    private void peso100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso100ActionPerformed
        // TODO add your handling code here:
        this.payment100 = peso100.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso100ActionPerformed

    private void peso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso5ActionPerformed
        // TODO add your handling code here:
        this.payment5 = peso5.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso5ActionPerformed

    private void FinTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinTransActionPerformed
        // TODO add your handling code here:
        if (payment1 == null && payment5 == null && payment10 == null && payment20 == null && payment50 == null && payment100 == null && payment200 == null && payment500 == null && payment1000 == null) {
            JOptionPane.showMessageDialog(null, """
                                                Make sure to fill out the text field with a valid input
                                                Don't forget to press enter at the Text Field before FINISH TRANSACTION                            
                                                """);
        } else {
            String payment = payment1 + "," + payment5 + "," + payment10 + "," + payment20 + "," + payment50 + "," + payment100 + "," + payment200 + "," + payment500 + "," + payment1000;
            System.out.println(payment);

            int totalPayment = RVM.calculateTotalPayment(payment);
            int price = 0;

            ChangeGUI next = new ChangeGUI();
            switch (RVM.selectedProduct) {
                case 1:
                    price = Product.BROWN_RICE.getPrice();
                    break;
                case 2:
                    price = Product.WHITE_RICE.getPrice();
                    break;
                case 3:
                    price = Product.JAVA_RICE.getPrice();
                    break;
                case 4:
                    price = Product.BACON_BITS.getPrice();
                    break;
                case 5:
                    price = Product.ROASTED_MUSHROOMS.getPrice();
                    break;
                case 6:
                    price = Product.EDAMAME.getPrice();
                    break;
                case 7:
                    price = Product.GRILLED_CHICKEN.getPrice();
                    break;
                case 8:
                    price = Product.GROUND_BEEF.getPrice();
                    break;
                case 9:
                    price = Product.MEATBALLS.getPrice();
                    break;
                case 10:
                    price = Product.SALMON.getPrice();
                    break;
                case 11:
                    price = Product.TERIYAKI.getPrice();
                    break;
                case 12:
                    price = Product.CHEESE.getPrice();
                    break;
            }

            int[] denominations = {1000, 500, 200, 100, 50, 20, 10, 5, 1};

            int changeAmount = totalPayment - price;
            int[] change = RVM.calculateChange(changeAmount, denominations);

            System.out.println("Change Amount: " + changeAmount);
            System.out.println("Change Denominations:");
            for (int i = 0; i < denominations.length; i++) {
                switch (i) {
                    case 0: next.Amount9.setText("Amount: " + change[i]);
                    break;
                    case 1: next.Amount8.setText("Amount: " + change[i]);
                    break;
                    case 2: next.Amount7.setText("Amount: " + change[i]);
                    break;
                    case 3: next.Amount6.setText("Amount: " + change[i]);
                    break;
                    case 4: next.Amount5.setText("Amount: " + change[i]);
                    break;
                    case 5: next.Amount4.setText("Amount: " + change[i]);
                    break;
                    case 6: next.Amount3.setText("Amount: " + change[i]);
                    break;
                    case 7: next.Amount2.setText("Amount: " + change[i]);
                    break;
                    case 8: next.Amount1.setText("Amount: " + change[i]);
                    break;
                }
                System.out.println("Payment " + denominations[i] + " = " + change[i]);
            }
            
            next.setVisible(true);
//            System.out.println(RVM.selectedProduct);
//            RVM.selectProduct(CST.chosenItem);
//            System.out.println("999");
//            System.out.println(RVM.selectedProduct);
//            int[] enteredPayment = Payment.parsePayment(payment);
//            RVM.storePayment(enteredPayment);
//            RVM.enterPayment(enteredPayment);
//           
//            String string1 = Integer.toString(change.pay1);
//            String string2 = Integer.toString(change.pay5);
//            String string3 = Integer.toString(change.pay10);
//            String string4 = Integer.toString(change.pay20);
//            String string5 = Integer.toString(change.pay50);
//            String string6 = Integer.toString(change.pay100);
//            String string7 = Integer.toString(change.pay200);
//            String string8 = Integer.toString(change.pay500);
//            String string9 = Integer.toString(change.pay1000);
//            
//            next.Amount2.setText("Amount: " + string2);
//            next.Amount3.setText("Amount: " + string3);
//            next.Amount4.setText("Amount: " + string4);
//            next.Amount5.setText("Amount: " + string5);
//            next.Amount6.setText("Amount: " + string6);
//            next.Amount7.setText("Amount: " + string7);
//            next.Amount8.setText("Amount: " + string8);
//            next.Amount9.setText("Amount: " + string9);
//            
//            next.setVisible(true);
        }


    }//GEN-LAST:event_FinTransActionPerformed


    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        CustomerRVGUI back = new CustomerRVGUI();
        RegularVendingMachine RVM = new RegularVendingMachine();

        int panel1 = 0;
        int panel2 = 0;
        int panel3 = 0;
        int panel4 = 0;
        int panel5 = 0;
        int panel6 = 0;
        int panel7 = 0;
        int panel8 = 0;
        int panel9 = 0;
        int panel10 = 0;
        int panel11 = 0;
        int panel12 = 0;

        RVM.forTheBackButton();
        for (int i = 0; i < 12; i++) {
            switch (i) {
                case 1:
                    panel1 = RVM.stock[i];
                    break;
                case 2:
                    panel2 = RVM.stock[i];
                    break;
                case 3:
                    panel3 = RVM.stock[i];
                    break;
                case 4:
                    panel4 = RVM.stock[i];
                    break;
                case 5:
                    panel5 = RVM.stock[i];
                    break;
                case 6:
                    panel6 = RVM.stock[i];
                    break;
                case 7:
                    panel7 = RVM.stock[i];
                    break;
                case 8:
                    panel8 = RVM.stock[i];
                    break;
                case 9:
                    panel9 = RVM.stock[i];
                    break;
                case 10:
                    panel10 = RVM.stock[i];
                    break;
                case 11:
                    panel11 = RVM.stock[i];
                    break;
                case 12:
                    panel12 = RVM.stock[i];
                    break;
            }
            back.itemStock1.setText("QUANTITY: " + panel1);
            back.itemStock2.setText("QUANTITY: " + panel2);
            back.itemStock3.setText("QUANTITY: " + panel3);
            back.itemStock4.setText("QUANTITY: " + panel4);
            back.itemStock5.setText("QUANTITY: " + panel5);
            back.itemStock6.setText("QUANTITY: " + panel6);
            back.itemStock7.setText("QUANTITY: " + panel7);
            back.itemStock8.setText("QUANTITY: " + panel8);
            back.itemStock9.setText("QUANTITY: " + panel9);
            back.itemStock10.setText("QUANTITY: " + panel10);
            back.itemStock11.setText("QUANTITY: " + panel11);
            back.itemStock12.setText("QUANTITY: " + panel12);

        }

        back.setVisible(true);

        //this.dispose();

    }//GEN-LAST:event_backActionPerformed

    private void peso50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso50ActionPerformed
        // TODO add your handling code here:
        this.payment50 = peso50.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso50ActionPerformed

    private void peso200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso200ActionPerformed
        // TODO add your handling code here:
        this.payment200 = peso200.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso200ActionPerformed

    private void peso500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso500ActionPerformed
        // TODO add your handling code here:
        this.payment500 = peso500.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso500ActionPerformed

    private void peso1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso1000ActionPerformed
        // TODO add your handling code here:
        this.payment1000 = peso1000.getText().strip();
        System.out.println(RVM.selectedProduct);
    }//GEN-LAST:event_peso1000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinTrans;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField peso1;
    public static javax.swing.JTextField peso10;
    public static javax.swing.JTextField peso100;
    public static javax.swing.JTextField peso1000;
    public static javax.swing.JTextField peso20;
    public static javax.swing.JTextField peso200;
    public static javax.swing.JTextField peso5;
    public static javax.swing.JTextField peso50;
    public static javax.swing.JTextField peso500;
    // End of variables declaration//GEN-END:variables
}
